name: Complex Job Flow
on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "job one"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "job two"
  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - run: echo "job three"
  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: echo "job four"
  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - run: echo "job five"
  job6:
    needs: [job4, job5]
    runs-on: ubuntu-latest
    steps:
      - run: echo "job six"